// -----------------------------------------------------------------------------
// Example (Optional) Mongoose Model: backend/models/SimulationRun.js
// You can create this file if you want to store metadata about simulation runs.
// -----------------------------------------------------------------------------
/*
const mongoose = require('mongoose');

const simulationRunSchema = new mongoose.Schema({
  userId: { // Example: if you have user authentication
    type: String, 
    // required: true 
  },
  hydrographFileName: {
    type: String,
    required: true
  },
  tideFileName: {
    type: String
  },
  executionTimeRequested: {
    type: Number,
    required: true
  },
  status: {
    type: String,
    enum: ['pending', 'processing', 'completed', 'failed'],
    default: 'pending'
  },
  pltOutputFileName: { // Name of the .PLT file generated by the model worker
    type: String 
  },
  // You could store a reference to where the PLT data is stored, 
  // or even small PLT data directly if it's not too large, though not recommended for large files.
  // pltDataReference: String, 
  errorMessage: {
    type: String
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  completedAt: {
    type: Date
  }
});

const SimulationRun = mongoose.model('SimulationRun', simulationRunSchema);

module.exports = SimulationRun;
*/
